#PROBLEMA 1
#Notas de 5 estudiantes, True=Mayor de edad

#1. VECTORES Y MATRICES
```{r}
#1.1 Crear 1 vector por cada estudiante con los 5 registros
S1=c(50.4,62.3,92.1,77.6,TRUE)
S2=c(41.7,87.9,75.3,72.4,FALSE)
S3=c(30.3,67.8,69.3,71.2,FALSE)
S4=c(65.4,85.1,92.3,96.8,TRUE)
S5=c(70.4,88.2,95.2,90.7,TRUE)

#1.2 Crear el vector students_vector
students_vector=c(S1,S2,S3,S4,S5)

#1.3 Construir matriz students_matrix que reciba students_vector, 5 filas y byrow verdadero
students_matrix=matrix(students_vector, byrow = TRUE, nrow = 5)
students_matrix

```

#2. NOMBRADO DE UNA MATRIZ

```{r}
#2.1 Crear vectores name_students y name_courses_legal_age
name_students=c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones","Tom Hill")

name_courses_legal_age=c("TIC", "Accounting", "Psychology", "Ethics","Legal_age")

#2.2 Usar los vectores para nombrer filas y columnas de la matriz students_vector
rownames(students_matrix)=name_students
colnames(students_matrix)=name_courses_legal_age
students_matrix

```

#3. rowSums, cbind

```{r}
#Crear vector total_grade_student con la suma de las notas de cada estudiante

total_grade_student=rowSums(students_matrix[,1:4])
```

```{r}
#Pegar vector total_grade_student con la matriz students_matrix usando cbind y asignar resultado a una nueva matriz results_students

results_students=cbind(total_grade_student,students_matrix)
```

#4. SELECCIONANDO ELEMENTOS DE MATRIZ

```{r}
#De la matriz results_students seleccionar fila 1,3 y 5 y columnas 2 y 4, almacenar resultado en selected_elements

selected_elements=results_students[c(1,3,5),c(2,4)]
print(selected_elements)
```
#5 DATA FRAMES

```{r}
#5.1 Construir Data Frame students_grades_df usando la matriz result_students como parámetro

students_grades_df=data.frame(results_students)

```

```{r}
#5.2 Usar subset en students_grades_df para filtrar: accounting >80 y legal_age=true
subset.data.frame(students_grades_df,subset=Accounting>80&Legal_age==TRUE)

```

#FUNCIONES, CONDICIONALES Y BUCLES

```{r}
#6.1 Construir función students_projection que recorra results_students
#6.2 poner condiciones a las notas obtenidas
students_projection=function(results_students){
    for (i in 1:nrow(results_students[,c(1:4)])){
    for (j in 1:ncol(results_students[,c(1:4)])) {
      #print(paste("Filas",i,"Columnas",j,results_students[i,j]))
      if(results_students[i,j]<=45){
        print(paste(results_students[i,j],"Student at risk"))
      }
      if(results_students[i,j]>45&results_students[i,j]<61){
        print(paste(results_students[i,j],"Student may be approved"))
      }
      
      if(results_students[i,j]>=61){
        print(paste(results_students[i,j],"Student approved"))
      }
      
    }
  }
}

students_projection(results_students)
```

#7 DATA FRAMES Y LAPPLY

```{r}
index_education=function(grade){
  index_education=(1+(grade/100))/(2)
}
students_grades_df[,c(1:4)]
```
```{r}
lapply(students_grades_df, index_education)
```


#8 MATH UTILITIES

```{r}
score_mean=c(mean((results_students[,c(1:4)])))
students_grades_df
```


